sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -t johnneal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnneal/docker-react npm run test -- --coverage